// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Dragonscale Team

//! Python bindings for the learned-sparse (SPLADE / BGE-M3) vector type.

use pyo3::prelude::*;
use pyo3::types::PyDict;
use uni_common::uni_sparse_vector::SparseVector;

/// A learned-sparse vector — `{term_id -> weight}` over a high-cardinality
/// vocabulary (e.g. a SPLADE-v3 sparse head over a ~30k-term BERT vocab).
///
/// Construct from parallel ``indices`` / ``values`` sequences, or from a
/// ``dict[int, float]`` mapping term ids to weights::
///
///     SparseVector([2, 9, 40], [0.7, 1.2, 0.3])
///     SparseVector.from_dict({2: 0.7, 9: 1.2, 40: 0.3})
///
/// Input does not need to be sorted or de-duplicated: term ids are sorted and
/// duplicate weights summed (the same canonicalization the query path applies),
/// so the stored form always satisfies the kernel's strictly-ascending
/// invariant. An empty vector (no terms) is valid.
#[pyclass(name = "SparseVector", frozen, eq, from_py_object)]
#[derive(Debug, Clone, PartialEq)]
pub struct PySparseVector {
    pub(crate) inner: SparseVector,
}

impl PySparseVector {
    /// Build a [`PySparseVector`] from `(term_id, weight)` pairs, canonicalizing
    /// via the kernel's lenient `from_pairs` (sort + sum duplicates).
    fn from_pairs(pairs: Vec<(u32, f32)>) -> PyResult<Self> {
        let inner = SparseVector::from_pairs(pairs).map_err(|e| {
            pyo3::exceptions::PyValueError::new_err(format!("invalid sparse vector: {e}"))
        })?;
        Ok(Self { inner })
    }
}

#[pymethods]
impl PySparseVector {
    /// Create a sparse vector from parallel ``indices`` and ``values`` lists.
    ///
    /// The two sequences must have equal length. Term ids are canonicalized
    /// (sorted, duplicates summed); weights must be finite.
    #[new]
    fn new(indices: Vec<u32>, values: Vec<f32>) -> PyResult<Self> {
        if indices.len() != values.len() {
            return Err(pyo3::exceptions::PyValueError::new_err(format!(
                "SparseVector: indices and values must have equal length ({} vs {})",
                indices.len(),
                values.len()
            )));
        }
        Self::from_pairs(indices.into_iter().zip(values).collect())
    }

    /// Create a sparse vector from a ``dict[int, float]`` of term id -> weight.
    #[staticmethod]
    fn from_dict(mapping: std::collections::HashMap<u32, f32>) -> PyResult<Self> {
        Self::from_pairs(mapping.into_iter().collect())
    }

    // ── Getters ──────────────────────────────────────────────────────

    /// The term ids, strictly ascending.
    #[getter]
    fn indices(&self) -> Vec<u32> {
        self.inner.indices().to_vec()
    }

    /// The weights, parallel to [`PySparseVector::indices`].
    #[getter]
    fn values(&self) -> Vec<f32> {
        self.inner.values().to_vec()
    }

    /// Number of non-zero terms.
    fn __len__(&self) -> usize {
        self.inner.len()
    }

    /// Return the `{term_id: weight}` mapping as a Python dict.
    fn to_dict<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyDict>> {
        let dict = PyDict::new(py);
        for (term, weight) in self.inner.indices().iter().zip(self.inner.values()) {
            dict.set_item(*term, *weight)?;
        }
        Ok(dict)
    }

    // ── Dunder methods ───────────────────────────────────────────────

    fn __repr__(&self) -> String {
        format!(
            "SparseVector(indices={:?}, values={:?})",
            self.inner.indices(),
            self.inner.values()
        )
    }

    // __eq__ auto-generated by #[pyclass(eq)]
}
