# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Dragonscale Team
"""
Type stubs for the Uni Graph Database Python bindings.

Uni is an embedded, multi-model graph database with OpenCypher queries,
Locy datalog evaluation, and columnar analytics.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator
from typing import Any

# =============================================================================
# Typed Exception Hierarchy
# =============================================================================

class UniError(Exception):
    """Base exception for all Uni database errors."""

    ...

# Database lifecycle
class UniNotFoundError(UniError):
    """Database path does not exist."""

    ...

class UniDatabaseLockedError(UniError):
    """Database is locked by another process."""

    ...

# Schema errors
class UniSchemaError(UniError):
    """Schema definition or migration error."""

    ...

class UniLabelNotFoundError(UniError):
    """Label not found in schema."""

    ...

class UniEdgeTypeNotFoundError(UniError):
    """Edge type not found in schema."""

    ...

class UniPropertyNotFoundError(UniError):
    """Property not found on entity."""

    ...

class UniIndexNotFoundError(UniError):
    """Index not found."""

    ...

class UniLabelAlreadyExistsError(UniError):
    """Label already exists in schema."""

    ...

class UniEdgeTypeAlreadyExistsError(UniError):
    """Edge type already exists in schema."""

    ...

class UniConstraintError(UniError):
    """Constraint violation."""

    ...

class UniInvalidIdentifierError(UniError):
    """Invalid identifier name."""

    ...

# Query & parse errors
class UniParseError(UniError):
    """Cypher or Locy parse error."""

    ...

class UniQueryError(UniError):
    """Query execution error."""

    ...

class UniTypeError(UniError):
    """Type mismatch error."""

    ...

# Transaction errors
class UniTransactionError(UniError):
    """Transaction error."""

    ...

class UniTransactionConflictError(UniError):
    """Transaction serialization conflict."""

    ...

class UniTransactionAlreadyCompletedError(UniError):
    """Transaction has already been committed or rolled back."""

    ...

class UniTransactionExpiredError(UniError):
    """Transaction exceeded its deadline."""

    ...

class UniCommitTimeoutError(UniError):
    """Transaction commit timed out waiting for the writer lock."""

    ...

# Resource limits
class UniMemoryLimitExceededError(UniError):
    """Query exceeded its memory limit."""

    ...

class UniTimeoutError(UniError):
    """Operation timed out."""

    ...

# Access control
class UniReadOnlyError(UniError):
    """Operation not supported on read-only database."""

    ...

class UniPermissionDeniedError(UniError):
    """Permission denied."""

    ...

# Storage & I/O
class UniStorageError(UniError):
    """Storage layer error."""

    ...

class UniIOError(UniError):
    """I/O error."""

    ...

class UniInternalError(UniError):
    """Internal error."""

    ...

# Snapshot
class UniSnapshotNotFoundError(UniError):
    """Snapshot not found."""

    ...

# Arguments
class UniInvalidArgumentError(UniError):
    """Invalid argument."""

    ...

# Concurrency
class UniWriteContextAlreadyActiveError(UniError):
    """A write context is already active on the session."""

    ...

class UniCancelledError(UniError):
    """Operation was cancelled."""

    ...

# Locy-specific
class UniStaleDerivedFactsError(UniError):
    """Derived facts are stale relative to the current database version."""

    ...

class UniRuleConflictError(UniError):
    """Locy rule conflict during promotion."""

    ...

class UniHookRejectedError(UniError):
    """A session hook rejected the operation."""

    ...

class UniLocyCompileError(UniError):
    """Locy program compilation error."""

    ...

class UniLocyRuntimeError(UniError):
    """Locy program runtime error."""

    ...

# =============================================================================
# Type System Enums
# =============================================================================

class CrdtType:
    """CRDT type for conflict-free replicated data."""

    @staticmethod
    def G_COUNTER() -> CrdtType: ...
    @staticmethod
    def G_SET() -> CrdtType: ...
    @staticmethod
    def OR_SET() -> CrdtType: ...
    @staticmethod
    def LWW_REGISTER() -> CrdtType: ...
    @staticmethod
    def LWW_MAP() -> CrdtType: ...
    @staticmethod
    def RGA() -> CrdtType: ...
    @staticmethod
    def VECTOR_CLOCK() -> CrdtType: ...
    @staticmethod
    def VC_REGISTER() -> CrdtType: ...

class DataType:
    """Data type for schema property definitions.

    Simple types are available as class attributes (e.g., ``DataType.STRING``).
    Parameterized types use factory methods (e.g., ``DataType.vector(128)``).
    """

    # Simple types
    @staticmethod
    def STRING() -> DataType: ...
    @staticmethod
    def INT32() -> DataType: ...
    @staticmethod
    def INT64() -> DataType: ...
    @staticmethod
    def FLOAT32() -> DataType: ...
    @staticmethod
    def FLOAT64() -> DataType: ...
    @staticmethod
    def BOOL() -> DataType: ...
    @staticmethod
    def TIMESTAMP() -> DataType: ...
    @staticmethod
    def DATE() -> DataType: ...
    @staticmethod
    def TIME() -> DataType: ...
    @staticmethod
    def DATETIME() -> DataType: ...
    @staticmethod
    def DURATION() -> DataType: ...
    @staticmethod
    def JSON() -> DataType: ...

    # Parameterized types
    @staticmethod
    def vector(dimensions: int) -> DataType: ...
    @staticmethod
    def list(element_type: DataType) -> DataType: ...
    @staticmethod
    def map(key_type: DataType, value_type: DataType) -> DataType: ...
    @staticmethod
    def crdt(crdt_type: CrdtType) -> DataType: ...

# =============================================================================
# ID Types
# =============================================================================

class Vid:
    """Vertex identifier (64-bit sequential ID)."""

    def __init__(self, id: int) -> None: ...
    def as_int(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Eid:
    """Edge identifier (64-bit sequential ID)."""

    def __init__(self, id: int) -> None: ...
    def as_int(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class UniId:
    """Universal content-addressed identifier (SHA3-256, multibase-encoded)."""

    def __init__(self, multibase: str) -> None: ...
    def to_multibase(self) -> str: ...
    def as_bytes(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# =============================================================================
# Data Classes — Query Results
# =============================================================================

class Value:
    """A tagged Uni value — opt-in wrapper for explicit type discrimination.

    Query results return native Python types by default. Use ``Value`` when
    you need to distinguish types explicitly.
    """

    @staticmethod
    def null() -> Value: ...
    @staticmethod
    def bool(v: bool) -> Value: ...
    @staticmethod
    def int(v: int) -> Value: ...
    @staticmethod
    def float(v: float) -> Value: ...
    @staticmethod
    def string(v: str) -> Value: ...
    @staticmethod
    def bytes(v: bytes) -> Value: ...
    @staticmethod
    def vector(v: list[float]) -> Value: ...
    @property
    def type_name(self) -> str: ...
    def is_null(self) -> bool: ...
    def is_bool(self) -> bool: ...
    def is_int(self) -> bool: ...
    def is_float(self) -> bool: ...
    def is_string(self) -> bool: ...
    def to_python(self) -> Any: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

class Row:
    """A query result row with named columns.

    Supports dict-like access (``row["name"]``, ``row[0]``) and
    conversion to a plain dict via ``row.to_dict()``.
    """

    @property
    def columns(self) -> list[str]: ...
    def get(self, column: str) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __getitem__(self, key: str | int) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __repr__(self) -> str: ...

class QueryMetrics:
    """Query performance metrics returned with every query result."""

    parse_time_ms: float
    plan_time_ms: float
    exec_time_ms: float
    total_time_ms: float
    rows_returned: int
    rows_scanned: int
    bytes_read: int
    plan_cache_hit: bool
    l0_reads: int
    storage_reads: int
    cache_hits: int

class QueryWarning:
    """A query warning emitted during execution (e.g., missing index)."""

    code: str
    message: str

class Node:
    """A graph node returned from a Cypher query.

    Provides graph-native attributes (``.id``, ``.labels``, ``.properties``)
    and dict-like property access (``node["name"]``, ``"name" in node``).
    """

    @property
    def id(self) -> Vid: ...
    @property
    def element_id(self) -> Vid: ...
    @property
    def labels(self) -> list[str]: ...
    @property
    def properties(self) -> dict[str, Any]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class Edge:
    """A graph edge (relationship) returned from a Cypher query.

    Provides graph-native attributes (``.id``, ``.type``, ``.start_id``,
    ``.end_id``, ``.properties``) and dict-like property access.
    """

    @property
    def id(self) -> Eid: ...
    @property
    def element_id(self) -> Eid: ...
    @property
    def type(self) -> str: ...
    @property
    def start_id(self) -> Vid: ...
    @property
    def end_id(self) -> Vid: ...
    @property
    def properties(self) -> dict[str, Any]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class Path:
    """A graph path (alternating sequence of nodes and edges).

    Supports ``len()`` (number of hops), interleaved indexing
    (``path[0]`` → first node, ``path[1]`` → first edge), and iteration.
    """

    @property
    def nodes(self) -> list[Node]: ...
    @property
    def edges(self) -> list[Edge]: ...
    @property
    def start(self) -> Node | None: ...
    @property
    def end(self) -> Node | None: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Node | Edge: ...
    def __iter__(self) -> Iterator[Node | Edge]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class QueryResult:
    """Rich query result with rows, metrics, warnings, and column names.

    Implements the sequence protocol: ``for row in result``, ``result[0]``,
    ``len(result)`` all work.
    """

    metrics: QueryMetrics
    warnings: list[QueryWarning]
    columns: list[str]

    @property
    def rows(self) -> list[Row]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Row: ...
    def __iter__(self) -> Iterator[Row]: ...
    def __bool__(self) -> bool: ...

class ExplainOutput:
    """Typed output from ``session.explain()``."""

    plan_text: str
    warnings: list[str]
    cost_estimates: Any
    index_usage: Any
    suggestions: Any

class ProfileOutput:
    """Typed output from ``session.profile()``."""

    total_time_ms: int
    peak_memory_bytes: int
    plan_text: str
    operators: Any

class LocyExplainOutput:
    """Typed output from ``session.explain_locy()``."""

    plan_text: str
    strata_count: int
    rule_names: list[str]
    has_recursive_strata: bool
    warnings: list[str]
    command_count: int

# =============================================================================
# Data Classes — Schema Info
# =============================================================================

class PropertyInfo:
    """Information about a property."""

    name: str
    data_type: str
    nullable: bool
    is_indexed: bool

class IndexInfo:
    """Information about an index."""

    name: str
    index_type: str
    properties: list[str]
    status: str

class ConstraintInfo:
    """Information about a constraint."""

    name: str
    constraint_type: str
    properties: list[str]
    enabled: bool

class LabelInfo:
    """Information about a vertex label."""

    name: str
    count: int
    properties: list[PropertyInfo]
    indexes: list[IndexInfo]
    constraints: list[ConstraintInfo]

class SnapshotInfo:
    """Information about a database snapshot."""

    snapshot_id: str
    name: str | None
    created_at: str
    version_hwm: int

class IndexRebuildTaskInfo:
    """Status of a background index rebuild task."""

    id: str
    label: str
    status: str
    created_at: str
    started_at: str | None
    completed_at: str | None
    error: str | None
    retry_count: int

class IndexDefinitionInfo:
    """Definition of an index in the schema."""

    name: str
    index_type: str
    label: str
    properties: list[str]
    state: str

# =============================================================================
# Data Classes — Bulk Loading
# =============================================================================

class BulkStats:
    """Statistics from a bulk loading operation."""

    vertices_inserted: int
    edges_inserted: int
    indexes_rebuilt: int
    duration_secs: float
    index_build_duration_secs: float
    index_task_ids: list[str]
    indexes_pending: bool

class BulkProgress:
    """Progress callback data during bulk loading."""

    phase: str
    rows_processed: int
    total_rows: int | None
    current_label: str | None
    elapsed_secs: float

# =============================================================================
# Data Classes — Locy
# =============================================================================

class LocyStats:
    """Statistics from a Locy program evaluation."""

    strata_evaluated: int
    total_iterations: int
    derived_nodes: int
    derived_edges: int
    evaluation_time_secs: float
    queries_executed: int
    mutations_executed: int
    peak_memory_bytes: int

class LocyResult:
    """Result of a Locy program evaluation."""

    derived: Any
    stats: Any
    command_results: Any
    warnings: Any
    approximate_groups: Any
    derived_fact_set: Any

    def has_warning(self, code: str) -> bool: ...
    def warnings_list(self) -> Any: ...
    def derived_facts(self, rule: str) -> list[dict[str, Any]] | None: ...
    def rows(self) -> list[dict[str, Any]] | None: ...
    def columns(self) -> list[str] | None: ...
    @property
    def iterations(self) -> int: ...

class CompiledProgram:
    """A compiled Locy program ready for evaluation."""

    @property
    def num_strata(self) -> int: ...
    @property
    def num_rules(self) -> int: ...
    @property
    def rule_names(self) -> list[str]: ...

class DerivedFactSet:
    """Opaque wrapper around a Locy-derived fact set.

    Obtained from ``LocyResult.derived_fact_set`` and passed to ``tx.apply()``.
    """

    @property
    def evaluated_at_version(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def fact_count(self) -> int: ...
    @property
    def vertices(self) -> dict[str, list[dict[str, Any]]]: ...
    @property
    def edges(self) -> list[dict[str, Any]]: ...
    def is_empty(self) -> bool: ...

# =============================================================================
# Data Classes — Compaction & Metrics
# =============================================================================

class CompactionStats:
    """Statistics from a compaction operation."""

    files_compacted: int
    bytes_before: int
    bytes_after: int
    duration_secs: float
    crdt_merges: int

class DatabaseMetrics:
    """Database-wide metrics snapshot."""

    l0_mutation_count: int
    l0_estimated_size_bytes: int
    schema_version: int
    uptime_secs: float
    active_sessions: int
    l1_run_count: int
    write_throttle_pressure: float
    compaction_in_progress: bool
    wal_size_bytes: int
    wal_lsn: int
    total_queries: int
    total_commits: int

class SessionMetrics:
    """Metrics for a session's lifetime."""

    session_id: str
    active_since_secs: float
    queries_executed: int
    locy_evaluations: int
    total_query_time_secs: float
    transactions_committed: int
    transactions_rolled_back: int
    total_rows_returned: int
    total_rows_scanned: int
    plan_cache_hits: int
    plan_cache_misses: int
    plan_cache_size: int

class SessionCapabilities:
    """Session capabilities snapshot."""

    can_write: bool
    can_pin: bool
    isolation: str
    has_notifications: bool
    write_lease: str | None

# =============================================================================
# Data Classes — Transaction & Mutation Results
# =============================================================================

class RulePromotionError:
    """A rule promotion error from a transaction commit."""

    rule_text: str
    error: str

class CommitResult:
    """Result of committing a transaction."""

    mutations_committed: int
    rules_promoted: int
    version: int
    started_at_version: int
    wal_lsn: int
    duration_secs: float
    rule_promotion_errors: list[RulePromotionError]

    def version_gap(self) -> int: ...

class ExecuteResult:
    """Result of a ``transaction.execute()`` call."""

    affected_rows: int
    nodes_created: int
    nodes_deleted: int
    relationships_created: int
    relationships_deleted: int
    properties_set: int
    labels_added: int
    labels_removed: int
    metrics: dict[str, Any]

class ApplyResult:
    """Result of applying a DerivedFactSet to a transaction."""

    facts_applied: int
    version_gap: int

# =============================================================================
# Data Classes — Xervo (ML Runtime)
# =============================================================================

class Message:
    """A message in a conversation (role + text content)."""

    role: str
    content: str

    def __init__(self, role: str, content: str) -> None: ...
    @staticmethod
    def user(text: str) -> Message: ...
    @staticmethod
    def assistant(text: str) -> Message: ...
    @staticmethod
    def system(text: str) -> Message: ...

class TokenUsage:
    """Token usage statistics from a generation call."""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int

class GenerationResult:
    """Result of a Xervo generation call."""

    text: str
    usage: TokenUsage | None

# =============================================================================
# Data Classes — Notifications & Coordination
# =============================================================================

class CommitNotification:
    """A commit notification describing the effects of a committed transaction."""

    version: int
    mutation_count: int
    labels_affected: list[str]
    edge_types_affected: list[str]
    rules_promoted: int
    timestamp: str
    tx_id: str
    session_id: str
    causal_version: int

class CancellationToken:
    """A cooperative cancellation token for long-running operations."""

    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...

class WriteLease:
    """Write lease configuration for multi-agent coordination."""

    @staticmethod
    def LOCAL() -> WriteLease: ...
    @staticmethod
    def DYNAMODB(table: str) -> WriteLease: ...

# =============================================================================
# Data Classes — Prepared Statements
# =============================================================================

class PyPreparedQuery:
    """A prepared Cypher query that can be executed multiple times."""

    def execute(self, params: dict[str, Any] | None = None) -> QueryResult: ...
    def query_text(self) -> str: ...
    def bind(self) -> PreparedQueryBinder: ...

# Alias for convenience — the Rust binding lacks name = "PreparedQuery"
PreparedQuery = PyPreparedQuery

class PreparedLocy:
    """A prepared Locy program that can be executed multiple times."""

    def execute(self, params: dict[str, Any] | None = None) -> LocyResult: ...
    def program_text(self) -> str: ...
    def bind(self) -> PreparedLocyBinder: ...

class PreparedQueryBinder:
    """A fluent binder for executing a prepared Cypher query."""

    def param(self, name: str, value: Any) -> PreparedQueryBinder: ...
    def execute(self) -> QueryResult: ...

class PreparedLocyBinder:
    """A fluent binder for executing a prepared Locy program."""

    def param(self, name: str, value: Any) -> PreparedLocyBinder: ...
    def execute(self) -> LocyResult: ...

# =============================================================================
# Data Classes — Commit Streams
# =============================================================================

class CommitStream:
    """A synchronous iterator over commit notifications."""

    def close(self) -> None: ...
    def __iter__(self) -> CommitStream: ...
    def __next__(self) -> CommitNotification | None: ...
    def __enter__(self) -> CommitStream: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

class WatchBuilder:
    """Builder for configuring a commit watch stream."""

    def labels(self, labels: list[str]) -> WatchBuilder: ...
    def edge_types(self, types: list[str]) -> WatchBuilder: ...
    def debounce(self, seconds: float) -> WatchBuilder: ...
    def exclude_session(self, session_id: str) -> WatchBuilder: ...
    def build(self) -> CommitStream: ...
    def build_async(self) -> AsyncCommitStream: ...

# =============================================================================
# Builder Classes — Uni
# =============================================================================

class UniBuilder:
    """Builder for creating or opening a Uni database."""

    @staticmethod
    def open(path: str) -> UniBuilder: ...
    @staticmethod
    def create(path: str) -> UniBuilder: ...
    @staticmethod
    def open_existing(path: str) -> UniBuilder: ...
    @staticmethod
    def temporary() -> UniBuilder: ...
    @staticmethod
    def in_memory() -> UniBuilder: ...
    def hybrid(self, local_path: str, remote_url: str) -> UniBuilder: ...
    def cache_size(self, bytes: int) -> UniBuilder: ...
    def parallelism(self, n: int) -> UniBuilder: ...
    def schema_file(self, path: str) -> UniBuilder: ...
    def xervo_catalog_from_str(self, json: str) -> UniBuilder: ...
    def xervo_catalog_from_file(self, path: str) -> UniBuilder: ...
    def cloud_config(self, config: dict[str, Any]) -> UniBuilder: ...
    def config(self, config: dict[str, Any]) -> UniBuilder: ...
    def batch_size(self, size: int) -> UniBuilder: ...
    def wal_enabled(self, enabled: bool) -> UniBuilder: ...
    def read_only(self) -> UniBuilder: ...
    def write_lease(self, lease: WriteLease) -> UniBuilder: ...
    def build(self) -> Uni: ...

# =============================================================================
# Builder Classes — Schema
# =============================================================================

class SchemaBuilder:
    """Builder for defining database schema."""

    def label(self, name: str) -> LabelBuilder: ...
    def edge_type(
        self, name: str, from_labels: list[str], to_labels: list[str]
    ) -> EdgeTypeBuilder: ...
    def apply(self) -> None: ...

class LabelBuilder:
    """Builder for defining a vertex label."""

    def property(self, name: str, data_type: str | DataType) -> LabelBuilder: ...
    def property_nullable(
        self, name: str, data_type: str | DataType
    ) -> LabelBuilder: ...
    def vector(self, name: str, dimensions: int) -> LabelBuilder: ...
    def index(
        self, property: str, index_type: str | dict[str, Any]
    ) -> LabelBuilder: ...
    def done(self) -> SchemaBuilder: ...
    def apply(self) -> None: ...

class EdgeTypeBuilder:
    """Builder for defining an edge type."""

    def property(self, name: str, data_type: str | DataType) -> EdgeTypeBuilder: ...
    def property_nullable(
        self, name: str, data_type: str | DataType
    ) -> EdgeTypeBuilder: ...
    def done(self) -> SchemaBuilder: ...
    def apply(self) -> None: ...

# =============================================================================
# Builder Classes — Session-Level Query Builders
# =============================================================================

class SessionQueryBuilder:
    """Fluent builder for parameterized read queries on a session."""

    def param(self, name: str, value: Any) -> SessionQueryBuilder: ...
    def params(self, params: dict[str, Any]) -> SessionQueryBuilder: ...
    def timeout(self, seconds: float) -> SessionQueryBuilder: ...
    def max_memory(self, bytes: int) -> SessionQueryBuilder: ...
    def cancellation_token(self, token: CancellationToken) -> SessionQueryBuilder: ...
    def fetch_all(self) -> QueryResult: ...
    def fetch_one(self) -> dict[str, Any] | None: ...
    def cursor(self) -> QueryCursor: ...

class SessionLocyBuilder:
    """Fluent builder for Locy evaluation on a session."""

    def param(self, name: str, value: Any) -> SessionLocyBuilder: ...
    def params(self, params: dict[str, Any]) -> SessionLocyBuilder: ...
    def timeout(self, seconds: float) -> SessionLocyBuilder: ...
    def max_iterations(self, n: int) -> SessionLocyBuilder: ...
    def with_config(
        self, config: dict[str, Any] | LocyConfig
    ) -> SessionLocyBuilder: ...
    def cancellation_token(self, token: CancellationToken) -> SessionLocyBuilder: ...
    def run(self) -> LocyResult: ...

class ProfileBuilder:
    """Fluent builder for profiling queries on a session."""

    def param(self, name: str, value: Any) -> ProfileBuilder: ...
    def run(self) -> tuple[QueryResult, ProfileOutput]: ...

# =============================================================================
# Builder Classes — Transaction Builders
# =============================================================================

class TransactionBuilder:
    """Builder for creating a transaction with options."""

    def timeout(self, seconds: float) -> TransactionBuilder: ...
    def isolation(self, level: str) -> TransactionBuilder: ...
    def start(self) -> Transaction: ...

class TxQueryBuilder:
    """Fluent builder for read queries within a transaction."""

    def param(self, name: str, value: Any) -> TxQueryBuilder: ...
    def timeout(self, seconds: float) -> TxQueryBuilder: ...
    def fetch_all(self) -> QueryResult: ...
    def fetch_one(self) -> dict[str, Any] | None: ...
    def execute(self) -> ExecuteResult: ...
    def cursor(self) -> QueryCursor: ...

class TxExecuteBuilder:
    """Fluent builder for mutations within a transaction."""

    def param(self, name: str, value: Any) -> TxExecuteBuilder: ...
    def timeout(self, seconds: float) -> TxExecuteBuilder: ...
    def run(self) -> ExecuteResult: ...

class TxLocyBuilder:
    """Fluent builder for Locy evaluation within a transaction."""

    def param(self, name: str, value: Any) -> TxLocyBuilder: ...
    def timeout(self, seconds: float) -> TxLocyBuilder: ...
    def max_iterations(self, n: int) -> TxLocyBuilder: ...
    def with_config(self, config: dict[str, Any] | LocyConfig) -> TxLocyBuilder: ...
    def cancellation_token(self, token: CancellationToken) -> TxLocyBuilder: ...
    def run(self) -> LocyResult: ...

class ApplyBuilder:
    """Fluent builder for applying derived facts."""

    def require_fresh(self, require: bool) -> ApplyBuilder: ...
    def max_version_gap(self, gap: int) -> ApplyBuilder: ...
    def run(self) -> ApplyResult: ...

# =============================================================================
# Builder Classes — Bulk Loading
# =============================================================================

class BulkWriterBuilder:
    """Builder for bulk data loading."""

    def defer_vector_indexes(self, defer: bool) -> BulkWriterBuilder: ...
    def defer_scalar_indexes(self, defer: bool) -> BulkWriterBuilder: ...
    def batch_size(self, size: int) -> BulkWriterBuilder: ...
    def async_indexes(self, async_: bool) -> BulkWriterBuilder: ...
    def validate_constraints(self, validate: bool) -> BulkWriterBuilder: ...
    def max_buffer_size_bytes(self, size: int) -> BulkWriterBuilder: ...
    def on_progress(
        self, callback: Callable[[BulkProgress], None]
    ) -> BulkWriterBuilder: ...
    def build(self) -> BulkWriter: ...

class BulkWriter:
    """High-performance bulk data loader."""

    def insert_vertices(
        self, label: str, vertices: list[dict[str, Any]]
    ) -> list[int]: ...
    def insert_edges(
        self,
        edge_type: str,
        edges: list[tuple[int, int, dict[str, Any]]],
    ) -> None: ...
    def stats(self) -> BulkStats: ...
    def touched_labels(self) -> list[str]: ...
    def touched_edge_types(self) -> list[str]: ...
    def commit(self) -> BulkStats: ...
    def abort(self) -> None: ...
    def __enter__(self) -> BulkWriter: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

# =============================================================================
# Builder Classes — Streaming Appender
# =============================================================================

class AppenderBuilder:
    """Builder for configurable streaming appenders."""

    def batch_size(self, size: int) -> AppenderBuilder: ...
    def defer_vector_indexes(self, defer: bool) -> AppenderBuilder: ...
    def max_buffer_size_bytes(self, size: int) -> AppenderBuilder: ...
    def build(self) -> StreamingAppender: ...

class StreamingAppender:
    """Streaming data appender for a single label."""

    def append(self, properties: dict[str, Any]) -> None: ...
    def write_batch(self, batch: Any) -> None: ...
    def finish(self) -> BulkStats: ...
    def abort(self) -> None: ...
    def buffered_count(self) -> int: ...
    def __enter__(self) -> StreamingAppender: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

# =============================================================================
# Builder Classes — Session Templates
# =============================================================================

class SessionTemplateBuilder:
    """Builder for pre-configured session templates."""

    def param(self, key: str, value: Any) -> SessionTemplateBuilder: ...
    def rules(self, program: str) -> SessionTemplateBuilder: ...
    def hook(self, hook: Any) -> SessionTemplateBuilder: ...
    def query_timeout(self, seconds: float) -> SessionTemplateBuilder: ...
    def transaction_timeout(self, seconds: float) -> SessionTemplateBuilder: ...
    def build(self) -> SessionTemplate: ...

class SessionTemplate:
    """A pre-configured session factory."""

    def create(self) -> Session: ...

# =============================================================================
# Query Cursor
# =============================================================================

class QueryCursor:
    """Streaming cursor for large result sets."""

    @property
    def columns(self) -> list[str]: ...
    def fetch_one(self) -> dict[str, Any] | None: ...
    def fetch_many(self, n: int) -> list[dict[str, Any]]: ...
    def fetch_all(self) -> list[dict[str, Any]]: ...
    def close(self) -> None: ...
    def __iter__(self) -> QueryCursor: ...
    def __next__(self) -> dict[str, Any]: ...
    def __enter__(self) -> QueryCursor: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

# =============================================================================
# Xervo (ML Runtime)
# =============================================================================

class Xervo:
    """Synchronous facade for embedding and text generation."""

    def is_available(self) -> bool: ...
    def embed(self, alias: str, texts: list[str]) -> list[list[float]]: ...
    def generate(
        self,
        alias: str,
        messages: list[Message | dict[str, Any]],
        max_tokens: int | None = None,
        temperature: float | None = None,
        top_p: float | None = None,
    ) -> GenerationResult: ...
    def generate_text(
        self,
        alias: str,
        prompt: str,
        max_tokens: int | None = None,
        temperature: float | None = None,
        top_p: float | None = None,
    ) -> GenerationResult: ...

# =============================================================================
# Session (Sync)
# =============================================================================

class Session:
    """A query session with scoped variables.

    Sessions are the primary scope for reads and the factory for transactions.
    Create via ``db.session()``.

    Example::

        session = db.session()
        session.set("threshold", 0.5)
        results = session.query("MATCH (n) WHERE n.score > $threshold RETURN n")
    """

    # --- Parameters ---
    def set(self, key: str, value: Any) -> Session: ...
    def set_all(self, params: dict[str, Any]) -> None: ...
    def get(self, key: str) -> Any | None: ...

    # --- Cypher Reads ---
    def query(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> QueryResult: ...
    def query_with(self, cypher: str) -> SessionQueryBuilder: ...
    def query_cursor(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> QueryCursor: ...

    # --- Locy ---
    def locy(
        self, program: str, params: dict[str, Any] | None = None
    ) -> LocyResult: ...
    def locy_with(self, program: str) -> SessionLocyBuilder: ...
    def register_rules(self, program: str) -> None: ...
    def clear_rules(self) -> None: ...
    def compile_locy(self, program: str) -> CompiledProgram: ...

    # --- Planning & Introspection ---
    def explain(self, cypher: str) -> ExplainOutput: ...
    def explain_locy(self, program: str) -> LocyExplainOutput: ...
    def profile(self, cypher: str) -> tuple[QueryResult, ProfileOutput]: ...
    def profile_with(self, cypher: str) -> ProfileBuilder: ...

    # --- Prepared Statements ---
    def prepare(self, cypher: str) -> PreparedQuery: ...
    def prepare_locy(self, program: str) -> PreparedLocy: ...

    # --- Transaction Factory ---
    def tx(self) -> Transaction: ...
    def tx_with(self) -> TransactionBuilder: ...

    # --- Version Pinning ---
    def pin_to_version(self, snapshot_id: str) -> None: ...
    def pin_to_timestamp(self, epoch_secs: float) -> None: ...
    def refresh(self) -> None: ...
    def is_pinned(self) -> bool: ...

    # --- Custom Functions ---
    def register_function(self, name: str, func: Callable[..., Any]) -> None: ...

    # --- Hooks & Notifications ---
    def add_hook(self, hook: Any) -> None: ...
    def watch(self) -> CommitStream: ...
    def watch_with(self) -> WatchBuilder: ...

    # --- Cancellation ---
    def cancel(self) -> None: ...
    def cancellation_token(self) -> CancellationToken: ...

    # --- Observability ---
    def id(self) -> str: ...
    def capabilities(self) -> SessionCapabilities: ...
    def metrics(self) -> SessionMetrics: ...

    # --- Context Manager ---
    def __enter__(self) -> Session: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

# =============================================================================
# Transaction (Sync)
# =============================================================================

class Transaction:
    """A database transaction with ACID guarantees.

    Use as a context manager for automatic rollback on error::

        with session.tx() as tx:
            tx.execute("CREATE (n:Person {name: 'Alice'})")
            tx.commit()
    """

    # --- Cypher Reads ---
    def query(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> QueryResult: ...
    def query_with(self, cypher: str) -> TxQueryBuilder: ...

    # --- Cypher Writes ---
    def execute(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> ExecuteResult: ...
    def execute_with(self, cypher: str) -> TxExecuteBuilder: ...

    # --- Locy ---
    def locy(
        self, program: str, params: dict[str, Any] | None = None
    ) -> LocyResult: ...
    def locy_with(self, program: str) -> TxLocyBuilder: ...

    # --- Apply DerivedFactSet ---
    def apply(self, derived: DerivedFactSet) -> ApplyResult: ...
    def apply_with(self, derived: DerivedFactSet) -> ApplyBuilder: ...

    # --- Rule Management ---
    def register_rules(self, program: str) -> None: ...
    def clear_rules(self) -> None: ...

    # --- Prepared Statements ---
    def prepare(self, cypher: str) -> PreparedQuery: ...
    def prepare_locy(self, program: str) -> PreparedLocy: ...

    # --- Lifecycle ---
    def commit(self) -> CommitResult: ...
    def rollback(self) -> None: ...
    def id(self) -> str: ...
    def started_at_version(self) -> int: ...
    def is_dirty(self) -> bool: ...
    def is_completed(self) -> bool: ...

    # --- Cancellation ---
    def cancel(self) -> None: ...
    def cancellation_token(self) -> CancellationToken: ...

    # --- Bulk Loading ---
    def bulk_writer(self) -> TxBulkWriterBuilder: ...
    def appender(self, label: str) -> StreamingAppender: ...
    def appender_builder(self, label: str) -> TxAppenderBuilder: ...

    # --- Context Manager ---
    def __enter__(self) -> Transaction: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

class TxBulkWriterBuilder:
    """Builder for configuring bulk data loading within a transaction."""
    def defer_vector_indexes(self, defer: bool) -> TxBulkWriterBuilder: ...
    def defer_scalar_indexes(self, defer: bool) -> TxBulkWriterBuilder: ...
    def batch_size(self, size: int) -> TxBulkWriterBuilder: ...
    def async_indexes(self, async_: bool) -> TxBulkWriterBuilder: ...
    def validate_constraints(self, validate: bool) -> TxBulkWriterBuilder: ...
    def max_buffer_size_bytes(self, size: int) -> TxBulkWriterBuilder: ...
    def on_progress(
        self, callback: Callable[[BulkProgress], None]
    ) -> TxBulkWriterBuilder: ...
    def build(self) -> BulkWriter: ...

class TxAppenderBuilder:
    """Builder for configuring a StreamingAppender within a transaction."""
    def batch_size(self, size: int) -> TxAppenderBuilder: ...
    def defer_vector_indexes(self, defer: bool) -> TxAppenderBuilder: ...
    def max_buffer_size_bytes(self, size: int) -> TxAppenderBuilder: ...
    def build(self) -> StreamingAppender: ...

# =============================================================================
# LocyConfig
# =============================================================================

class LocyConfig:
    """Configuration for Locy program evaluation."""
    def __init__(
        self,
        max_iterations: int | None = None,
        timeout_secs: float | None = None,
        max_explain_depth: int | None = None,
        max_slg_depth: int | None = None,
        max_abduce_candidates: int | None = None,
        max_abduce_results: int | None = None,
        max_derived_bytes: int | None = None,
        deterministic_best_by: bool | None = None,
        strict_probability_domain: bool | None = None,
        probability_epsilon: float | None = None,
        exact_probability: bool | None = None,
        max_bdd_variables: int | None = None,
        top_k_proofs: int | None = None,
        top_k_proofs_training: int | None = None,
    ) -> None: ...
    @property
    def max_iterations(self) -> int: ...
    @property
    def timeout_secs(self) -> float: ...
    @property
    def max_explain_depth(self) -> int: ...
    @property
    def max_slg_depth(self) -> int: ...
    @property
    def max_abduce_candidates(self) -> int: ...
    @property
    def max_abduce_results(self) -> int: ...
    @property
    def max_derived_bytes(self) -> int: ...
    @property
    def deterministic_best_by(self) -> bool: ...
    @property
    def strict_probability_domain(self) -> bool: ...
    @property
    def probability_epsilon(self) -> float: ...
    @property
    def exact_probability(self) -> bool: ...
    @property
    def max_bdd_variables(self) -> int: ...
    @property
    def top_k_proofs(self) -> int: ...
    @property
    def top_k_proofs_training(self) -> int | None: ...

# =============================================================================
# Schema
# =============================================================================

class Schema:
    """A read-only snapshot of the database schema."""
    @property
    def version(self) -> int: ...
    @property
    def label_names(self) -> list[str]: ...
    @property
    def edge_type_names(self) -> list[str]: ...
    @property
    def label_count(self) -> int: ...
    @property
    def edge_type_count(self) -> int: ...
    def label_info(self, name: str) -> LabelInfo | None: ...

# =============================================================================
# CommandResult Classes
# =============================================================================

class QueryCommandResult:
    """Result from a Locy QUERY command."""
    @property
    def command_type(self) -> str: ...
    @property
    def rows(self) -> list[dict[str, Any]]: ...
    def __getitem__(self, key: str) -> Any: ...

class AssumeCommandResult:
    """Result from a Locy ASSUME command."""
    @property
    def command_type(self) -> str: ...
    @property
    def rows(self) -> list[dict[str, Any]]: ...
    def __getitem__(self, key: str) -> Any: ...

class ExplainCommandResult:
    """Result from a Locy EXPLAIN command."""
    @property
    def command_type(self) -> str: ...
    @property
    def tree(self) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...

class AbduceCommandResult:
    """Result from a Locy ABDUCE command."""
    @property
    def command_type(self) -> str: ...
    @property
    def modifications(self) -> list[dict[str, Any]]: ...
    def __getitem__(self, key: str) -> Any: ...

class DeriveCommandResult:
    """Result from a Locy DERIVE command."""
    @property
    def command_type(self) -> str: ...
    affected: int
    def __getitem__(self, key: str) -> Any: ...

class CypherCommandResult:
    """Result from a Locy CYPHER command."""
    @property
    def command_type(self) -> str: ...
    @property
    def rows(self) -> list[dict[str, Any]]: ...
    def __getitem__(self, key: str) -> Any: ...

# =============================================================================
# Hook Context Types
# =============================================================================

class HookContext:
    """Context passed to session hooks before/after query execution."""

    session_id: str
    query_text: str
    query_type: str

class CommitHookContext:
    """Context passed to session hooks before/after transaction commit."""

    session_id: str
    tx_id: str
    mutation_count: int

class QueryType:
    """Query type discriminator for hook contexts."""
    @staticmethod
    def CYPHER() -> str: ...
    @staticmethod
    def LOCY() -> str: ...
    @staticmethod
    def EXECUTE() -> str: ...

# =============================================================================
# Uni (Sync)
# =============================================================================

class Uni:
    """
    The main synchronous Uni database interface.

    Uni is lifecycle and admin. It opens, shuts down, manages schema,
    and stamps out Sessions. It does not execute queries or mutations.

    Example::

        db = Uni.temporary()
        db.schema().label("Person").property("name", "String").apply()
        session = db.session()
        session.execute("CREATE (n:Person {name: 'Alice'})")
        results = session.query("MATCH (n:Person) RETURN n.name AS name")
    """

    # Static Factories
    @staticmethod
    def open(path: str) -> Uni: ...
    @staticmethod
    def temporary() -> Uni: ...
    @staticmethod
    def in_memory() -> Uni: ...
    @staticmethod
    def create(path: str) -> Uni: ...
    @staticmethod
    def open_existing(path: str) -> Uni: ...
    @staticmethod
    def builder() -> UniBuilder: ...

    # Session Factory
    def session(self) -> Session: ...
    def session_template(self) -> SessionTemplateBuilder: ...

    # Schema DDL & Inspection
    def schema(self) -> SchemaBuilder: ...
    def label_exists(self, name: str) -> bool: ...
    def edge_type_exists(self, name: str) -> bool: ...
    def list_labels(self) -> list[str]: ...
    def list_edge_types(self) -> list[str]: ...
    def get_label_info(self, name: str) -> LabelInfo | None: ...
    def get_schema(self) -> dict[str, Any]: ...
    def get_schema_typed(self) -> Schema: ...
    def load_schema(self, path: str) -> None: ...
    def save_schema(self, path: str) -> None: ...

    # Global Locy Rules
    def register_rules(self, program: str) -> None: ...
    def clear_rules(self) -> None: ...

    # Xervo
    def xervo(self) -> Xervo: ...

    # Storage Admin
    def flush(self) -> None: ...
    def compact_label(self, label: str) -> CompactionStats: ...
    def compact_edge_type(self, edge_type: str) -> CompactionStats: ...
    def wait_for_compaction(self) -> None: ...

    # Snapshots
    def create_snapshot(self, name: str | None = None) -> str: ...
    def list_snapshots(self) -> list[SnapshotInfo]: ...
    def restore_snapshot(self, snapshot_id: str) -> None: ...

    # Index Admin
    def rebuild_indexes(self, label: str, background: bool = False) -> str | None: ...
    def index_rebuild_status(self) -> list[IndexRebuildTaskInfo]: ...
    def retry_index_rebuilds(self) -> list[str]: ...
    def is_index_building(self, label: str) -> bool: ...
    def list_indexes(self, label: str) -> list[IndexDefinitionInfo]: ...
    def list_all_indexes(self) -> list[IndexDefinitionInfo]: ...

    # Observability & Lifecycle
    def metrics(self) -> DatabaseMetrics: ...
    def config(self) -> dict[str, Any]: ...
    def write_lease(self) -> WriteLease | None: ...
    def shutdown(self) -> None: ...

    # Context Manager
    def __enter__(self) -> Uni: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

# =============================================================================
# Async API — Uni Builder
# =============================================================================

class AsyncUniBuilder:
    """Async builder for creating and configuring an AsyncUni instance."""

    @staticmethod
    def open(path: str) -> AsyncUniBuilder: ...
    @staticmethod
    def open_existing(path: str) -> AsyncUniBuilder: ...
    @staticmethod
    def create(path: str) -> AsyncUniBuilder: ...
    @staticmethod
    def temporary() -> AsyncUniBuilder: ...
    @staticmethod
    def in_memory() -> AsyncUniBuilder: ...
    def hybrid(self, local_path: str, remote_url: str) -> AsyncUniBuilder: ...
    def cache_size(self, bytes: int) -> AsyncUniBuilder: ...
    def parallelism(self, n: int) -> AsyncUniBuilder: ...
    def schema_file(self, path: str) -> AsyncUniBuilder: ...
    def xervo_catalog_from_str(self, json: str) -> AsyncUniBuilder: ...
    def xervo_catalog_from_file(self, path: str) -> AsyncUniBuilder: ...
    def cloud_config(self, config: dict[str, Any]) -> AsyncUniBuilder: ...
    def config(self, config: dict[str, Any]) -> AsyncUniBuilder: ...
    def batch_size(self, size: int) -> AsyncUniBuilder: ...
    def wal_enabled(self, enabled: bool) -> AsyncUniBuilder: ...
    def read_only(self) -> AsyncUniBuilder: ...
    def write_lease(self, lease: WriteLease) -> AsyncUniBuilder: ...
    async def build(self) -> AsyncUni: ...

# =============================================================================
# Async API — Uni
# =============================================================================

class AsyncUni:
    """
    The main asynchronous Uni database interface.

    Example::

        db = await AsyncUni.temporary()
        await db.schema().label("Person").property("name", "String").apply()
        session = db.session()
        await session.execute("CREATE (n:Person {name: 'Alice'})")
        results = await session.query("MATCH (n:Person) RETURN n.name AS name")
    """

    @staticmethod
    async def open(path: str) -> AsyncUni: ...
    @staticmethod
    async def temporary() -> AsyncUni: ...
    @staticmethod
    async def create(path: str) -> AsyncUni: ...
    @staticmethod
    async def open_existing(path: str) -> AsyncUni: ...
    @staticmethod
    async def in_memory() -> AsyncUni: ...
    @staticmethod
    def builder() -> AsyncUniBuilder: ...

    # Session Factory
    def session(self) -> AsyncSession: ...
    def session_template(self) -> SessionTemplateBuilder: ...

    # Schema DDL & Inspection
    def schema(self) -> AsyncSchemaBuilder: ...
    async def label_exists(self, name: str) -> bool: ...
    async def edge_type_exists(self, name: str) -> bool: ...
    async def list_labels(self) -> list[str]: ...
    async def list_edge_types(self) -> list[str]: ...
    async def get_label_info(self, name: str) -> LabelInfo | None: ...
    def get_schema(self) -> dict[str, Any]: ...
    def get_schema_typed(self) -> Schema: ...
    async def load_schema(self, path: str) -> None: ...
    async def save_schema(self, path: str) -> None: ...

    # Global Locy Rules
    def register_rules(self, program: str) -> None: ...
    def clear_rules(self) -> None: ...

    # Xervo
    def xervo(self) -> AsyncXervo: ...

    # Storage Admin
    async def flush(self) -> None: ...
    async def compact_label(self, label: str) -> CompactionStats: ...
    async def compact_edge_type(self, edge_type: str) -> CompactionStats: ...
    async def wait_for_compaction(self) -> None: ...

    # Snapshots
    async def create_snapshot(self, name: str | None = None) -> str: ...
    async def list_snapshots(self) -> list[SnapshotInfo]: ...
    async def restore_snapshot(self, snapshot_id: str) -> None: ...

    # Index Admin
    async def rebuild_indexes(
        self, label: str, background: bool = False
    ) -> str | None: ...
    async def index_rebuild_status(self) -> list[IndexRebuildTaskInfo]: ...
    async def retry_index_rebuilds(self) -> list[str]: ...
    async def is_index_building(self, label: str) -> bool: ...
    def list_indexes(self, label: str) -> list[IndexDefinitionInfo]: ...
    def list_all_indexes(self) -> list[IndexDefinitionInfo]: ...

    # Observability & Lifecycle
    def metrics(self) -> DatabaseMetrics: ...
    def config(self) -> dict[str, Any]: ...
    def write_lease(self) -> WriteLease | None: ...
    async def shutdown(self) -> None: ...

    # Context Manager
    async def __aenter__(self) -> AsyncUni: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

# =============================================================================
# Async API — Session
# =============================================================================

class AsyncSession:
    """An async query session with scoped variables.

    Sessions are the primary scope for reads and the factory for transactions.
    Create via ``db.session()``.
    """

    # --- Parameters ---
    async def set(self, key: str, value: Any) -> None: ...
    async def set_all(self, params: dict[str, Any]) -> None: ...
    async def get(self, key: str) -> Any | None: ...

    # --- Cypher Reads ---
    async def query(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> QueryResult: ...
    def query_with(self, cypher: str) -> AsyncSessionQueryBuilder: ...
    async def query_cursor(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> AsyncQueryCursor: ...

    # --- Locy ---
    async def locy(
        self, program: str, params: dict[str, Any] | None = None
    ) -> LocyResult: ...
    def locy_with(self, program: str) -> AsyncSessionLocyBuilder: ...
    async def register_rules(self, program: str) -> None: ...
    async def clear_rules(self) -> None: ...
    async def compile_locy(self, program: str) -> CompiledProgram: ...

    # --- Planning & Introspection ---
    async def explain(self, cypher: str) -> ExplainOutput: ...
    async def explain_locy(self, program: str) -> LocyExplainOutput: ...
    async def profile(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> tuple[QueryResult, ProfileOutput]: ...
    def profile_with(self, cypher: str) -> AsyncSessionProfileBuilder: ...

    # --- Prepared Statements ---
    async def prepare(self, cypher: str) -> PreparedQuery: ...
    async def prepare_locy(self, program: str) -> PreparedLocy: ...

    # --- Transaction Factory ---
    async def tx(self, timeout: float | None = None) -> AsyncTransaction: ...
    def tx_with(self) -> AsyncTransactionBuilder: ...

    # --- Version Pinning ---
    async def pin_to_version(self, snapshot_id: str) -> None: ...
    async def pin_to_timestamp(self, epoch_secs: float) -> None: ...
    async def refresh(self) -> None: ...
    async def is_pinned(self) -> bool: ...

    # --- Custom Functions ---
    async def register_function(self, name: str, func: Callable[..., Any]) -> None: ...

    # --- Hooks & Notifications ---
    async def add_hook(self, hook: Any) -> None: ...
    async def watch(self) -> AsyncCommitStream: ...
    async def watch_with(self) -> WatchBuilder: ...

    # --- Cancellation ---
    async def cancel(self) -> None: ...
    async def cancellation_token(self) -> CancellationToken: ...

    # --- Observability ---
    async def id(self) -> str: ...
    async def capabilities(self) -> SessionCapabilities: ...
    async def metrics(self) -> SessionMetrics: ...

    # --- Context Manager ---
    async def __aenter__(self) -> AsyncSession: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

# =============================================================================
# Async API — Transaction
# =============================================================================

class AsyncTransaction:
    """An async database transaction with context manager support.

    Example::

        async with await session.tx() as tx:
            await tx.execute("CREATE (n:Person {name: 'Alice'})")
            await tx.commit()
    """

    # --- Cypher Reads ---
    async def query(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> QueryResult: ...
    def query_with(self, cypher: str) -> AsyncTxQueryBuilder: ...

    # --- Cypher Writes ---
    async def execute(
        self, cypher: str, params: dict[str, Any] | None = None
    ) -> ExecuteResult: ...
    def execute_with(self, cypher: str) -> AsyncTxExecuteBuilder: ...

    # --- Locy ---
    async def locy(
        self, program: str, params: dict[str, Any] | None = None
    ) -> LocyResult: ...
    def locy_with(self, program: str) -> AsyncTxLocyBuilder: ...

    # --- Apply DerivedFactSet ---
    async def apply(
        self,
        derived: DerivedFactSet,
        require_fresh: bool = False,
        max_version_gap: int | None = None,
    ) -> ApplyResult: ...
    async def apply_with(self, derived: DerivedFactSet) -> AsyncApplyBuilder: ...

    # --- Rule Management ---
    async def register_rules(self, program: str) -> None: ...
    async def clear_rules(self) -> None: ...

    # --- Prepared Statements ---
    async def prepare(self, cypher: str) -> PreparedQuery: ...
    async def prepare_locy(self, program: str) -> PreparedLocy: ...

    # --- Lifecycle ---
    async def commit(self) -> CommitResult: ...
    async def rollback(self) -> None: ...
    async def id(self) -> str: ...
    async def started_at_version(self) -> int: ...
    async def is_dirty(self) -> bool: ...
    async def is_completed(self) -> bool: ...

    # --- Cancellation ---
    async def cancel(self) -> None: ...
    async def cancellation_token(self) -> CancellationToken: ...

    # --- Bulk Loading ---
    def bulk_writer(self) -> AsyncTxBulkWriterBuilder: ...
    async def appender(self, label: str) -> StreamingAppender: ...

    # --- Context Manager ---
    async def __aenter__(self) -> AsyncTransaction: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

class AsyncTxBulkWriterBuilder:
    """Async builder for configuring bulk data loading within a transaction."""
    def defer_vector_indexes(self, defer: bool) -> AsyncTxBulkWriterBuilder: ...
    def defer_scalar_indexes(self, defer: bool) -> AsyncTxBulkWriterBuilder: ...
    def batch_size(self, size: int) -> AsyncTxBulkWriterBuilder: ...
    def async_indexes(self, async_: bool) -> AsyncTxBulkWriterBuilder: ...
    def validate_constraints(self, validate: bool) -> AsyncTxBulkWriterBuilder: ...
    def max_buffer_size_bytes(self, size: int) -> AsyncTxBulkWriterBuilder: ...
    def on_progress(
        self, callback: Callable[[BulkProgress], None]
    ) -> AsyncTxBulkWriterBuilder: ...
    async def build(self) -> AsyncBulkWriter: ...

# =============================================================================
# Async API — Session-Level Builders
# =============================================================================

class AsyncSessionQueryBuilder:
    """Async fluent builder for parameterized read queries on a session."""

    def param(self, name: str, value: Any) -> AsyncSessionQueryBuilder: ...
    def params(self, params: dict[str, Any]) -> AsyncSessionQueryBuilder: ...
    def timeout(self, seconds: float) -> AsyncSessionQueryBuilder: ...
    def max_memory(self, bytes: int) -> AsyncSessionQueryBuilder: ...
    def cancellation_token(
        self, token: CancellationToken
    ) -> AsyncSessionQueryBuilder: ...
    async def fetch_all(self) -> QueryResult: ...
    async def fetch_one(self) -> dict[str, Any] | None: ...
    async def cursor(self) -> AsyncQueryCursor: ...

class AsyncSessionLocyBuilder:
    """Async fluent builder for Locy evaluation on a session."""

    def param(self, name: str, value: Any) -> AsyncSessionLocyBuilder: ...
    def params(self, params: dict[str, Any]) -> AsyncSessionLocyBuilder: ...
    def timeout(self, seconds: float) -> AsyncSessionLocyBuilder: ...
    def max_iterations(self, n: int) -> AsyncSessionLocyBuilder: ...
    def with_config(
        self, config: dict[str, Any] | LocyConfig
    ) -> AsyncSessionLocyBuilder: ...
    def cancellation_token(
        self, token: CancellationToken
    ) -> AsyncSessionLocyBuilder: ...
    async def run(self) -> LocyResult: ...

class AsyncSessionProfileBuilder:
    """Async fluent builder for profiling queries on a session."""

    def param(self, name: str, value: Any) -> AsyncSessionProfileBuilder: ...
    def params(self, params: dict[str, Any]) -> AsyncSessionProfileBuilder: ...
    async def run(self) -> tuple[QueryResult, ProfileOutput]: ...

# =============================================================================
# Async API — Transaction-Level Builders
# =============================================================================

class AsyncTransactionBuilder:
    """Async builder for creating a transaction with options."""

    def timeout(self, seconds: float) -> AsyncTransactionBuilder: ...
    def isolation(self, level: str) -> AsyncTransactionBuilder: ...
    async def start(self) -> AsyncTransaction: ...

class AsyncTxQueryBuilder:
    """Async fluent builder for read queries within a transaction."""

    def param(self, name: str, value: Any) -> AsyncTxQueryBuilder: ...
    def timeout(self, seconds: float) -> AsyncTxQueryBuilder: ...
    async def fetch_all(self) -> QueryResult: ...
    async def fetch_one(self) -> dict[str, Any] | None: ...
    async def execute(self) -> ExecuteResult: ...
    async def cursor(self) -> AsyncQueryCursor: ...

class AsyncTxExecuteBuilder:
    """Async fluent builder for mutations within a transaction."""

    def param(self, name: str, value: Any) -> AsyncTxExecuteBuilder: ...
    def timeout(self, seconds: float) -> AsyncTxExecuteBuilder: ...
    async def run(self) -> ExecuteResult: ...

class AsyncTxLocyBuilder:
    """Async fluent builder for Locy evaluation within a transaction."""

    def param(self, name: str, value: Any) -> AsyncTxLocyBuilder: ...
    def timeout(self, seconds: float) -> AsyncTxLocyBuilder: ...
    def max_iterations(self, n: int) -> AsyncTxLocyBuilder: ...
    def with_config(
        self, config: dict[str, Any] | LocyConfig
    ) -> AsyncTxLocyBuilder: ...
    def cancellation_token(self, token: CancellationToken) -> AsyncTxLocyBuilder: ...
    async def run(self) -> LocyResult: ...

class AsyncApplyBuilder:
    """Async fluent builder for applying derived facts."""

    def require_fresh(self, require: bool) -> AsyncApplyBuilder: ...
    def max_version_gap(self, gap: int) -> AsyncApplyBuilder: ...
    async def run(self) -> ApplyResult: ...

# =============================================================================
# Async API — Bulk Loading
# =============================================================================

class AsyncBulkWriterBuilder:
    """Async builder for bulk data loading."""

    def defer_vector_indexes(self, defer: bool) -> AsyncBulkWriterBuilder: ...
    def defer_scalar_indexes(self, defer: bool) -> AsyncBulkWriterBuilder: ...
    def batch_size(self, size: int) -> AsyncBulkWriterBuilder: ...
    def async_indexes(self, async_: bool) -> AsyncBulkWriterBuilder: ...
    def validate_constraints(self, validate: bool) -> AsyncBulkWriterBuilder: ...
    def max_buffer_size_bytes(self, size: int) -> AsyncBulkWriterBuilder: ...
    def on_progress(
        self, callback: Callable[[BulkProgress], None]
    ) -> AsyncBulkWriterBuilder: ...
    async def build(self) -> AsyncBulkWriter: ...

class AsyncBulkWriter:
    """Async bulk writer for high-throughput data ingestion."""

    async def insert_vertices(
        self, label: str, vertices: list[dict[str, Any]]
    ) -> list[int]: ...
    async def insert_edges(
        self,
        edge_type: str,
        edges: list[tuple[int, int, dict[str, Any]]],
    ) -> None: ...
    def stats(self) -> BulkStats: ...
    def touched_labels(self) -> list[str]: ...
    def touched_edge_types(self) -> list[str]: ...
    async def commit(self) -> BulkStats: ...
    async def abort(self) -> None: ...
    async def __aenter__(self) -> AsyncBulkWriter: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

# =============================================================================
# Async API — Query Streaming
# =============================================================================

class AsyncQueryBuilder:
    """Async builder for parameterized queries."""

    def param(self, name: str, value: Any) -> AsyncQueryBuilder: ...
    def params(self, params: dict[str, Any]) -> AsyncQueryBuilder: ...
    def timeout(self, seconds: float) -> AsyncQueryBuilder: ...
    def max_memory(self, bytes: int) -> AsyncQueryBuilder: ...
    async def cursor(self) -> AsyncQueryCursor: ...
    async def execute(self) -> int: ...
    async def fetch_all(self) -> QueryResult: ...

class AsyncQueryCursor:
    """Async streaming cursor for large result sets."""

    @property
    def columns(self) -> list[str]: ...
    async def fetch_one(self) -> dict[str, Any] | None: ...
    async def fetch_many(self, n: int) -> list[dict[str, Any]]: ...
    async def fetch_all(self) -> list[dict[str, Any]]: ...
    async def close(self) -> None: ...
    async def __aiter__(self) -> AsyncQueryCursor: ...
    async def __anext__(self) -> dict[str, Any]: ...
    async def __aenter__(self) -> AsyncQueryCursor: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

class AsyncCommitStream:
    """Async iterator over commit notifications."""

    async def close(self) -> None: ...
    def __aiter__(self) -> AsyncCommitStream: ...
    async def __anext__(self) -> CommitNotification: ...

# =============================================================================
# Async API — Schema
# =============================================================================

class AsyncSchemaBuilder:
    """Async builder for defining database schema."""

    def label(self, name: str) -> AsyncLabelBuilder: ...
    def edge_type(
        self, name: str, from_labels: list[str], to_labels: list[str]
    ) -> AsyncEdgeTypeBuilder: ...
    async def apply(self) -> None: ...

class AsyncLabelBuilder:
    """Async builder for defining a vertex label."""

    def property(self, name: str, data_type: str | DataType) -> AsyncLabelBuilder: ...
    def property_nullable(
        self, name: str, data_type: str | DataType
    ) -> AsyncLabelBuilder: ...
    def vector(self, name: str, dimensions: int) -> AsyncLabelBuilder: ...
    def index(
        self, property: str, index_type: str | dict[str, Any]
    ) -> AsyncLabelBuilder: ...
    def done(self) -> AsyncSchemaBuilder: ...
    async def apply(self) -> None: ...

class AsyncEdgeTypeBuilder:
    """Async builder for defining an edge type."""

    def property(
        self, name: str, data_type: str | DataType
    ) -> AsyncEdgeTypeBuilder: ...
    def property_nullable(self, name: str, data_type: str) -> AsyncEdgeTypeBuilder: ...
    def done(self) -> AsyncSchemaBuilder: ...
    async def apply(self) -> None: ...

# =============================================================================
# Async API — Xervo (ML Runtime)
# =============================================================================

class AsyncXervo:
    """Async facade for embedding and text generation."""

    def is_available(self) -> bool: ...
    async def embed(self, alias: str, texts: list[str]) -> list[list[float]]: ...
    async def generate(
        self,
        alias: str,
        messages: list[Message | dict[str, Any]],
        max_tokens: int | None = None,
        temperature: float | None = None,
        top_p: float | None = None,
    ) -> GenerationResult: ...
    async def generate_text(
        self,
        alias: str,
        prompt: str,
        max_tokens: int | None = None,
        temperature: float | None = None,
        top_p: float | None = None,
    ) -> GenerationResult: ...
